// import { type Metadata } from "next";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Quiz App - Learn Better",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   // 🔐 Build үед алдаа гарахаас сэргийлж түлхүүрийг энд авна
//   const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

//   return (
//     // publishableKey-г заавал ийм байдлаар дамжуулж өгнө. 
//     // Хэрэв байхгүй бол хоосон текст биш undefined байх ёстой.
//     <ClerkProvider publishableKey={clerkKey}>
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <header className="flex justify-between items-center p-4 gap-4 h-16 border">
//             <p className="ml-6 text-2xl font-semibold bg-gradient-to-r from-pink-400 via-[#6c47ff] to-violet-500 bg-size-[200%_200%] bg-clip-text text-transparent">
//               Quiz App
//             </p>
//             <div className="items-center p-4 gap-4 h-16 flex">
//               <SignedOut>
//                 <SignInButton mode="modal">
//                   <span className="cursor-pointer font-medium text-sm text-[#5b3ce6] hover:text-[#6c47ff] hover:underline">
//                     Sign In
//                   </span>
//                 </SignInButton>
//                 <SignUpButton mode="modal">
//                   <button className="bg-[#6c47ff] hover:bg-[#5b3ce6] text-white rounded-full font-medium h-10 px-4 cursor-pointer">
//                     Sign Up
//                   </button>
//                 </SignUpButton>
//               </SignedOut>
//               <SignedIn>
//                 <UserButton />
//               </SignedIn>
//             </div>
//           </header>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }


import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Quiz App - Learn Better',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // .env файлаас key-г уншиж авна
  const clerkKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

  return (
    <ClerkProvider publishableKey={clerkKey}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16 border">
            <p className="ml-6 text-2xl font-semibold bg-gradient-to-r from-pink-400 via-[#6c47ff] to-violet-500 bg-clip-text text-transparent bg-[length:200%_200%] transition-all duration-300">
              Quiz App
            </p>
            <div className="flex items-center gap-4">
              <SignedOut>
                <SignInButton mode="modal">
                  <span className="cursor-pointer font-medium text-sm text-[#5b3ce6] hover:text-[#6c47ff] hover:underline">
                    Sign In
                  </span>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button className="bg-[#6c47ff] hover:bg-[#5b3ce6] text-white rounded-full font-medium h-10 px-4 transition-colors">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </div>
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}