import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center p-4 gap-4 h-16">
            <p
              className="ml-6 text-2xl font-semibold   bg-gradient-to-r
      from-pink-400
      via-[#6c47ff]
      to-violet-500
      bg-size-[200%_200%]
      bg-clip-text text-transparent
      transition-all duration-300
      hover:bg-position-[100%_0]"
            >
              Quiz App
            </p>
            <div className=" items-center p-4 gap-4 h-16 flex">
              <SignedOut>
                <SignInButton>
                  <span className="cursor-pointer font-medium text-sm text-[#5b3ce6] sm:text-base transition-colors duration-200 hover:text-[#6c47ff] hover:underline">
                    Sign In
                  </span>
                </SignInButton>

                <SignUpButton>
                  <button className="bg-[#6c47ff] hover:bg-[#5b3ce6] transition-colors duration-200 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>

              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
